### ISSUE TITLE
Version 1.1.5 (F-Droid) crashes on start

### ISSUE THREAD

**Issue by Self-Perfection** [redfish64/TinyTravelTracker#36]
```
08-15 12:28:42.412 28154 28345 E AndroidRuntime: FATAL EXCEPTION: main
08-15 12:28:42.412 28154 28345 E AndroidRuntime: java.lang.NullPointerException
08-15 12:28:42.412 28154 28345 E AndroidRuntime:        at com.rareventure.gps2.reviewer.map.GpsLocationOverlay.resetMapData(GpsLocationOverlay.java:133)
08-15 12:28:42.412 28154 28345 E AndroidRuntime:        at com.rareventure.gps2.reviewer.map.GpsLocationOverlay.onLocationChanged(GpsLocationOverlay.java:126)
08-15 12:28:42.412 28154 28345 E AndroidRuntime:        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:263)
08-15 12:28:42.412 28154 28345 E AndroidRuntime:        at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:196)
08-15 12:28:42.412 28154 28345 E AndroidRuntime:        at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:219)
08-15 12:28:42.412 28154 28345 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
08-15 12:28:42.412 28154 28345 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:137)
08-15 12:28:42.412 28154 28345 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:4781)
08-15 12:28:42.412 28154 28345 E AndroidRuntime:        at java.lang.reflect.Method.invokeNative(Native Method)
08-15 12:28:42.412 28154 28345 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Method.java:511)
08-15 12:28:42.412 28154 28345 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:805)
08-15 12:28:42.412 28154 28345 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:568)
08-15 12:28:42.412 28154 28345 E AndroidRuntime:        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by redfish64** [comment]
I can't reproduce this, but it looks like events are happening in a different sequence compared to my phone, causing a variable to be read before it's initialized. I attempted to fix this and put it in version 1.1.7. It should be in f-droid in a day or two, hopefully, and in google play in a few hours.

**Comment by redfish64** [comment]
1.1.7 is up on F-Droid

**Comment by Self-Perfection** [comment]
I tried 1.1.7 and is does not crash.

Does not look to me that it starts absolutely correct, seems that I need to tap app icon more than once. Does it just starts slowly? I'm not sure but, I defenitely don't see crashes in logs anymore, so I assume this is resolved.

BTW, after start I get #37
