### ISSUE TITLE
[Crash] crashing when opening app

### ISSUE THREAD

**Issue by gsurrel** [redfish64/TinyTravelTracker#57]
The map wasn't downloading the vector tiles anymore so I exported my GPS data, reset the app data and then re-import. The indexing seemed fine but the media doesn't. Here is the logcat screenshot of the crash I could get from my phone: http://i.imgur.com/j9AyewV.jpg

**Comment by gsurrel** [comment]
Here is a more complete stacktrace from the crash:

```
03-13 16:49:03.441 816-844/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.rareventure.gps2/.reviewer.map.OsmMapGpsTrailerReviewerMapActivity bnds=[677,295][862,500]} from uid 10097 on display 0
                                                
                                                --------- beginning of main
03-13 16:49:03.673 30104-30104/? D/GpsTrailer: Starting on intent Intent { cmp=com.rareventure.gps2/.GpsTrailerService }
03-13 16:49:03.674 30104-30104/? D/GpsTrailer: Starting on intent Intent { cmp=com.rareventure.gps2/.GpsTrailerService }
03-13 16:49:03.739 816-881/? I/ActivityManager: Displayed com.rareventure.gps2/.reviewer.map.OsmMapGpsTrailerReviewerMapActivity: +275ms (total +15s914ms)
03-13 16:49:03.856 17501-17526/? D/conversations: deleted file /storage/emulated/0/Android/data/com.rareventure.gps2/files/cache.td.rf.tmp
03-13 16:49:03.858 17501-17526/? D/conversations: deleted file /storage/emulated/0/Android/data/com.rareventure.gps2/files/MediaLocTime.tt.rf.tmp
03-13 16:49:03.863 30104-28095/? E/GpsTrailer: Thread Thread[Thread-43264,5,main]: trace: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:423), com.rareventure.gps2.GpsTrailerGpsStrategy$GpsBatteryManager$1.run(GpsTrailerGpsStrategy.java:407)]
03-13 16:49:03.863 30104-28095/? E/GpsTrailer: Thread Thread[Thread-43269,5,main]: trace: [dalvik.system.VMStack.getThreadStackTrace(Native Method), java.lang.Thread.getStackTrace(Thread.java:580), java.lang.Thread.getAllStackTraces(Thread.java:522), com.rareventure.android.Util.printAllStackTraces(Util.java:1066), com.rareventure.gps2.database.cachecreator.GpsTrailerCacheCreator.run(GpsTrailerCacheCreator.java:414)]
03-13 16:49:03.864 30104-28095/? E/GpsTrailer: Thread SelectedAreaSet [isRunning=true, isShutdown=false, rwtm=com.rareventure.util.ReadWriteThreadManager@3b0d87e, activity=com.rareventure.gps2.reviewer.map.OsmMapGpsTrailerReviewerMapActivity@92d57ff, requestedAreas=[], requestedStartTimeSec=0, requestedEndTimeSec=0, resultPaths=null, resultTimeRangeTree=[], resultAreas=[], resultEndTime=0, resultStartTime=0, upToDate=true, distCalculated=true, timeZone=libcore.util.ZoneInfo[id="Europe/Zurich",mRawOffset=3600000,mEarliestRawOffset=3600000,mUseDst=true,mDstSavings=3600000,transitions=118], p1=Point(0, 0), p2=Point(0, 0), lastTimeRange=null, lastIndex=0, observers=[android.widget.AbsListView$AdapterDataSetObserver@3b6c1df], getTimeRangeTr=AreaTimeRange [fullRangeStartSec=0, fullRangeEndSec=0, dist=0.0, startTimeSec=0, endTimeSec=0], workerInterrupted=false, resultIncomplete=false, upToDateLock=java.lang.Object@55cae2c, t1TimeRange=AreaTimeRange [fullRangeStartSec=0, fullRangeEndSec=0, dist=0.0, startTimeSec=0, endTimeSec=0], t2TimeRange=AreaTimeRange [fullRangeStartSec=0, fullRangeEndSec=0, dist=0.0, startTimeSec=0, endTimeSec=0], resultId=1, isResultTimeTree=true]: trace: [java.lang.Object.wait(Native Method), com.rareventure.gps2.reviewer.map.sas.SelectedAreaSet.run(SelectedAreaSet.java:297)]
03-13 16:49:03.864 30104-28095/? E/ACRA: ACRA caught a NegativeArraySizeException for com.rareventure.gps2
                                         java.lang.NegativeArraySizeException: -1241509888
                                             at android.media.ExifInterface.readImageFileDirectory(ExifInterface.java:2023)
                                             at android.media.ExifInterface.readImageFileDirectory(ExifInterface.java:2041)
                                             at android.media.ExifInterface.readImageFileDirectory(ExifInterface.java:2014)
                                             at android.media.ExifInterface.readExifSegment(ExifInterface.java:1863)
                                             at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1662)
                                             at android.media.ExifInterface.loadAttributes(ExifInterface.java:1339)
                                             at android.media.ExifInterface.<init>(ExifInterface.java:1057)
                                             at com.rareventure.gps2.reviewer.map.MediaLocTimeMap.updateFromGallery(MediaLocTimeMap.java:348)
                                             at com.rareventure.gps2.database.cachecreator.GpsTrailerCacheCreator.run(GpsTrailerCacheCreator.java:372)
03-13 16:49:03.923 30104-28095/? E/ACRA: Not adding buildConfig to log. Class Not found : com.rareventure.gps2.BuildConfig. Please configure 'buildConfigClass' in your ACRA config
03-13 16:49:03.978 30104-28235/? D/ACRA: Looking for error files in /data/user/0/com.rareventure.gps2/files
03-13 16:49:03.979 30104-28235/? D/ACRA: Looking for error files in /data/user/0/com.rareventure.gps2/files
03-13 16:49:04.382 30104-28236/? E/AndroidRuntime: FATAL EXCEPTION: Thread-43269
                                                   Process: com.rareventure.gps2, PID: 30104
                                                   Theme: themes:{default=overlay:de.baumann.thema, iconPack:system, fontPkg:de.baumann.thema, com.android.systemui=overlay:de.baumann.thema, com.android.systemui.navbar=overlay:de.baumann.thema}
                                                   java.lang.NegativeArraySizeException: -1241509888
                                                       at android.media.ExifInterface.readImageFileDirectory(ExifInterface.java:2023)
                                                       at android.media.ExifInterface.readImageFileDirectory(ExifInterface.java:2041)
                                                       at android.media.ExifInterface.readImageFileDirectory(ExifInterface.java:2014)
                                                       at android.media.ExifInterface.readExifSegment(ExifInterface.java:1863)
                                                       at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1662)
                                                       at android.media.ExifInterface.loadAttributes(ExifInterface.java:1339)
                                                       at android.media.ExifInterface.<init>(ExifInterface.java:1057)
                                                       at com.rareventure.gps2.reviewer.map.MediaLocTimeMap.updateFromGallery(MediaLocTimeMap.java:348)
                                                       at com.rareventure.gps2.database.cachecreator.GpsTrailerCacheCreator.run(GpsTrailerCacheCreator.java:372)
03-13 16:49:04.388 816-574/? W/ActivityManager:   Force finishing activity com.rareventure.gps2/.reviewer.map.OsmMapGpsTrailerReviewerMapActivity
```
The [NegativeArraySizeException raised in the ExifInterface init](https://github.com/redfish64/TinyTravelTracker/blob/cdf63f3fcb69c2c8aaf01577c8ecd776689c6c0f/app/src/main/java/com/rareventure/gps2/reviewer/map/MediaLocTimeMap.java#L348) seems to be [fixed upstream](https://github.com/android/platform_frameworks_base/commit/582e612fdc8fe0afd66d03abfccdfbc8b4b77792), but now it seems like a good idea to catch it here directly, no?
