### ISSUE TITLE
Tiles not appearing

### ISSUE THREAD

**Issue by NitroNils** [redfish64/TinyTravelTracker#79]
Tiles not showing. Only white background.

Version 1.1.38
On android 6.1
Huawei P8 lite.

**Comment by sbechet** [comment]
Same here.

**Comment by baumanno** [comment]
Some more info on this:
TinyTravelTracker, F_Droid build, v1.1.38 from May 26 2018

Ran `adb logcat > logcat.txt; grep -i 'tangr' logcat.txt` and got the following output:

```
06-20 19:04:45.481  1977  1977 D Tangram : TANGRAM map.cpp:229: Loading scene file: asset:///map_style.yaml
06-20 19:04:45.592  1977  1977 D Tangram : WARNING texture.cpp:274: OpenGL ES doesn't support texture repeat wrapping for NPOT textures nor mipmap textures
06-20 19:04:45.592  1977  1977 D Tangram : WARNING texture.cpp:275: Falling back to LINEAR Filtering
06-20 19:04:45.663  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_route_line for layer mz_route_line
06-20 19:04:45.663  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_dash_line for layer mz_route_line_dash
06-20 19:04:45.663  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_route_line_transit for layer mz_route_line_transit
06-20 19:04:45.663  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_current_location for layer mz_current_location_gem
06-20 19:04:45.663  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_route_location for layer mz_route_location
06-20 19:04:45.663  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_route_start for layer mz_route_start
06-20 19:04:45.663  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_route_stop for layer mz_route_stop
06-20 19:04:45.663  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_route_transit_stop for layer mz_route_transit_stop
06-20 19:04:45.663  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_search_result for layer mz_search_result
06-20 19:04:45.664  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_dropped_pin for layer mz_dropped_pin
06-20 19:04:45.664  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_default_point for layer mz_default_point
06-20 19:04:45.664  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_default_shield for layer mz_default_shield
06-20 19:04:45.664  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_default_line for layer mz_default_line
06-20 19:04:45.664  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source mz_default_polygon for layer mz_default_polygon
06-20 19:04:45.664  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source gt_point for layer gt_point
06-20 19:04:45.664  1977  1977 D Tangram : WARNING sceneLoader.cpp:1731: Can't find data source gt_selected_area_rect for layer gt_selected_area_rect
06-20 19:04:45.669  1977  1977 D Tangram : WARNING styleParam.cpp:160: Unknown StyleParam cull_from_tile:true
06-20 19:04:45.669  1977  1977 D Tangram : WARNING styleParam.cpp:160: Unknown StyleParam filter:$zoom:max:14
06-20 19:04:45.669  1977  1977 D Tangram : WARNING styleParam.cpp:160: Unknown StyleParam draw:mapzen_icon_library:visible:false
06-20 19:04:45.703  1977  1977 D Tangram : NOTIFY tileManager.cpp:72: add source mapzen
06-20 19:04:45.898  1977 18673 D Tangram : TANGRAM map.cpp:907: setup GL
06-20 19:04:45.928  1977 18673 D Tangram : TANGRAM hardware.cpp:60: Driver supports map buffer: 0
06-20 19:04:45.929  1977 18673 D Tangram : TANGRAM hardware.cpp:61: Driver supports vaos: 1
06-20 19:04:45.929  1977 18673 D Tangram : TANGRAM hardware.cpp:62: Driver supports rgb8_rgba8: 1
06-20 19:04:45.929  1977 18673 D Tangram : TANGRAM hardware.cpp:63: Driver supports NPOT texture: 0
06-20 19:04:45.931  1977 18673 D Tangram : TANGRAM hardware.cpp:77: Hardware max texture size 4096
06-20 19:04:45.932  1977 18673 D Tangram : TANGRAM hardware.cpp:78: Hardware max combined texture units 32
06-20 19:04:45.937  1977 18673 D Tangram : TANGRAM map.cpp:381: resize: 1440 x 2296
06-20 19:04:45.962  1977 18676 D Tangram : TANGRAM tileWorker.cpp:51: Passed new TileBuilder to TileWorker
06-20 19:04:45.962  1977 18675 D Tangram : TANGRAM tileWorker.cpp:51: Passed new TileBuilder to TileWorker
06-20 19:04:47.553  1977 18693 D Tangram : ERROR networkDataSource.cpp:70: Error for URL request 'https://free.tilehosting.com/data/v3/10/545/356.pbf.pict?key=F4sTzzXiI7pfgslJxUx': 
06-20 19:04:47.563  1977 18693 D OkHttp  : 	at com.mapzen.tangram.MapController$13.onResponse(MapController.java:1343)
06-20 19:04:47.672  1977 18715 D Tangram : ERROR networkDataSource.cpp:70: Error for URL request 'https://free.tilehosting.com/data/v3/10/545/355.pbf.pict?key=F4sTzzXiI7pfgslJxUx': 
06-20 19:04:47.673  1977 18715 D OkHttp  : 	at com.mapzen.tangram.MapController$13.onResponse(MapController.java:1343)
06-20 19:04:47.687  1977 18696 D Tangram : ERROR networkDataSource.cpp:70: Error for URL request 'https://free.tilehosting.com/data/v3/10/544/355.pbf.pict?key=F4sTzzXiI7pfgslJxUx': 
06-20 19:04:47.687  1977 18696 D OkHttp  : 	at com.mapzen.tangram.MapController$13.onResponse(MapController.java:1343)
06-20 19:04:47.812  1977 18705 D Tangram : ERROR networkDataSource.cpp:70: Error for URL request 'https://free.tilehosting.com/data/v3/10/545/354.pbf.pict?key=F4sTzzXiI7pfgslJxUx': 
06-20 19:04:47.814  1977 18705 D OkHttp  : 	at com.mapzen.tangram.MapController$13.onResponse(MapController.java:1343)
06-20 19:04:47.829  1977 18694 D Tangram : ERROR networkDataSource.cpp:70: Error for URL request 'https://free.tilehosting.com/data/v3/10/544/356.pbf.pict?key=F4sTzzXiI7pfgslJxUx': 
06-20 19:04:47.830  1977 18694 D OkHttp  : 	at com.mapzen.tangram.MapController$13.onResponse(MapController.java:1343)
06-20 19:04:47.916  1977 18693 D Tangram : ERROR networkDataSource.cpp:70: Error for URL request 'https://free.tilehosting.com/data/v3/10/544/354.pbf.pict?key=F4sTzzXiI7pfgslJxUx': 
06-20 19:04:47.917  1977 18693 D OkHttp  : 	at com.mapzen.tangram.MapController$13.onResponse(MapController.java:1343)
```

Hitting those URLs at the bottom with a browser gives the response `Invalid key`.

Let me know if you need more info!

**Comment by redfish64** [comment]
Sorry, they changed something on the website. This happened at a very bad time for me (visiting family) so I wasn't able to fix it right away. I'll upload the fix today.

**Comment by baumanno** [comment]
Just pulled 1.1.39 from F-Droid and can confirm the tiles appear again.
Thanks for the fix! :)

**Comment by NitroNils** [comment]
Yes, it is working again!

[Now how can I close this? Using FastHub Libre.)

**Comment by sbechet** [comment]
Right for me too! Thank you very much.

**Comment by johnea** [comment]
Hello, I'm seeing this with version 1.1.40 from f-droid.

It worked at first, but has stopped and restarting app or rebooting doesn't correct...

**Comment by johnea** [comment]
Thank You! I'll watch for the update on f-droid...
